### ISSUE TITLE
GameOfLife. Не работает Play

### ISSUE THREAD

**Issue by thmsystem** [biblelamp/JavaExercises#1]
Программа компилируется и запускается, работает FillRandom, NextGeneration, но почему-то не работает Кнопка Play, иконка сменяется на "Паузу", но жизнь не идет.

тоже самое и при запуске GameOfLife.jar

-------
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

**Comment by biblelamp** [comment]
Странная ситуация, не могу повторить у себя эту ошибку. Попробуйте загрузить самый последний релиз jre - 1.8.0_102 и отпишите пожалуйста - какой будет результат.

**Comment by thmsystem** [comment]
Скачал последнюю java, установил, перезагрузился. Никаких изменений.

может это из-за того, что я запускаю приложение на Mac?
У меня OS X El Capitan 10.11.6

хотя все, должно кроссплатформенно работать..

**Comment by biblelamp** [comment]
Печальный факт, возьму на заметку. Вот такая она кроссплатформенность... Должно-то должно, но как видим, есть разница. Я запускаю JVM под Windows. Интересно будет проверить в Linux...
